u-boot-toradex-fw-utils_git.bb: fix fw_setenv on apalis-tk1-mainline
The eMMC unlocking was missing which lead to the following error
message:

Write error on /dev/mmcblk0boot0: Operation not permitted
Error: can't write fw_env to flash

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Stefan Agner <stefan.agner@toradex.com>